load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "banking-lib-utilities",
    srcs = glob(["**/src/*.cc"]),
    hdrs = glob(["**/include/*.h"]),
    visibility = ["//visibility:public"],
    alwayslink=1
)