#include<iostream>
#include<map>
#include "../include/uid_type.h"
#include "../include/uid_alphanumeric.h"


using namespace std;

namespace banking_lib_utilities {
    map<string, UIDGenerator<string>*> UIDAlphaNumeric::pools;

    bool UIDAlphaNumeric::create_UIDPool(string pool_name){
        /*
         * create_UIDPool will create a uid pool based on pool name
         * :param pool_name: Name of the pool
         * :type pool_name: string
         * :return bool true or false on successful creation of pool
         */
        UIDGenerator<string>* pool = UIDAlphaNumeric::get_uid_pool(pool_name); 
        if ( pool == NULL) {
            pool = new UIDGenerator<string>(ALPHA_NUMERIC);
            if (pool == NULL) {
                cout<<"Error Creating AlphaNumeric UIDPool"<<endl;
                return false;
            }
            UIDAlphaNumeric::pools.insert(make_pair(pool_name, pool));    
        }
        return true;
    }
    UIDGenerator<string>* UIDAlphaNumeric::get_uid_pool(string pool_name){
        /*
         * get_uid_pool api will get the corresponding id_pool, given a pool_name.
         * :param pool_name: name of the pool
         * :type pool_name: string
         * :return UIDGenerator instance for template type string 
         * rtype: UIDGenerator<string>*
         */
        auto itr = UIDAlphaNumeric::pools.find(pool_name);
        if (itr == UIDAlphaNumeric::pools.end()){
            return NULL;
        }
        return itr->second;
    }

    list<string> UIDAlphaNumeric::get_available_uid_pool(){
        /*
         * get_available_uid_pools will get all the available pool_names
         * :return list of pool_names
         * :rtype: list<string>
         */
        list<string> available_pools;
        for (auto itr = UIDAlphaNumeric::pools.begin();
                itr != UIDAlphaNumeric::pools.end(); itr++){
            available_pools.push_back(itr->first);
        }
        return available_pools;
    }

    string UIDAlphaNumeric::get_new_uid(string pool_name){
        /*
         * get_new_uid will get a new uid from the pool
         * :param pool_name: name of the pool to be used
         * :type pool_name: string
         * :return new alphanumeric id
         * :rtypr: string
         */
        auto pool = UIDAlphaNumeric::get_uid_pool(pool_name);
        if (pool == NULL) {
            cout<<"Couldn't find the pool for "<<pool_name<<endl;
            return string();
        }
        return pool->create_new_uid();

    }
    bool UIDAlphaNumeric::release_uid(string pool_name, string uid){
        /*
         * release_uid will release the given id from the pool_name
         * :param pool_name: name of the pool to be used
         * :type pool_name: string
         * :param uid: uid which was generated by generator
         * :type uid: string
         * :return true if id released else false
         * :rtype: bool
         */
        auto pool = UIDAlphaNumeric::get_uid_pool(pool_name);
        if (pool == NULL) {
            cout<<"Couldn't find the pool for "<<pool_name<<endl;
            return false;
        }
        return pool->release_uid(uid);
    }

    bool UIDAlphaNumeric::uid_exists(string pool_name, string uid){
        /*
         * uid_exists will check if the given uid exists in the pool_name
         * :param pool_name: name of the pool to be used
         * :type pool_name: string
         * :param uid: unique identifier
         * :type uid: string
         * :return true if the id exists else false
         */
        auto pool = UIDAlphaNumeric::get_uid_pool(pool_name);
        if (pool == NULL) {
            cout<<"Couldn't find the pool for "<<pool_name<<endl;
            return false;
        }
        return pool->uid_exists(uid);
    }
    list<string> UIDAlphaNumeric::get_all_allocated_uid(string pool_name){
        /*
         * get_all_allocated_uid will get all the allocated ids from pool
         * :param pool_name: name of the pool to be used
         * :type pool_name: string
         * :return list of the unique ids
         * :rtype list<string>
         */
        auto pool = UIDAlphaNumeric::get_uid_pool(pool_name);
        if (pool == NULL) {
            cout<<"Couldn't find the pool for "<<pool_name<<endl;
            //return empty list
            return list<string>();
        }
        return pool->get_all_allocated_uid();        

    }


}